rootPageId: 1
base: 'https://www.epoche-napoleon.net'
baseVariants:
  -
    base: 'https://www.epoche-napoleon.net'
    condition: 'applicationContext == "Production"'
  -
    base: 'http://composer.epoche-napoleon.net'
    condition: 'applicationContext == "Development"'
languages:
  -
    title: Deutsch
    enabled: true
    languageId: '0'
    base: /
    typo3Language: de
    locale: de_DE
    iso-639-1: de
    navigationTitle: ''
    hreflang: de
    direction: ltr
    flag: de
errorHandling:
  -
    errorCode: '403'
    errorHandler: Page
    errorContentSource: '21'
  -
    errorCode: '404'
    errorHandler: Page
    errorContentSource: '6851'
  -
    errorCode: '500'
    errorHandler: Page
    errorContentSource: '7398'
  -
    errorCode: '503'
    errorHandler: Page
    errorContentSource: '6848'
routes:
  -
    route: robot.txt
    type: staticText
    content: "User-agent: *\r\nDisallow: /typo3/\r\nDisallow: /typo3_src/\r\nDisallow: /template/\r\nAllow: /typo3/sysext/frontend/Resources/Public/*\r\nAllow: /template/Resources/Public/*"
routeEnhancers:
  PageTypeSuffix:
    type: PageType
    default: .html
    index: index
    map:
      .html: 0
      rss.feed: 9818
      sitemap.xml: 1533906435
  Glossary2Plugin:
    type: Extbase
    limitToPages: [407]
    extension: Glossary2
    plugin: Glossary
    routes:
      -
        routePath: '/first-glossary-page'
        _controller: 'Glossary::list'
      -
        routePath: '/glossary-page-{page}'
        _controller: 'Glossary::list'
        _arguments:
          page: '@widget_0/currentPage'
      -
        routePath: '/glossary-by-letter/{letter}'
        _controller: 'Glossary::list'
      -
        routePath: '/show/{glossary_title}'
        _controller: 'Glossary::show'
        _arguments:
          glossary_title: glossary
    requirements:
      letter: '^(0-9|[a-z])$'
      glossary_title: '^[a-zA-Z0-9]+\-[0-9]+$'
    defaultController: 'Glossary::list'
    aspects:
      glossary_title:
        type: PersistedAliasMapper
        tableName: tx_glossary2_domain_model_glossary
        routeFieldName: path_segment
  News:
    type: Extbase
    limitToPages:
      - 25
      - 26
      - 874
      - 6530
    extension: News
    plugin: Pi1
    routes:
      -
        routePath: '{news_page}'
        _controller: 'News::list'
        _arguments:
          news_page: '@widget_0/currentPage'
      -
        routePath: '/news_title}'
        _controller: 'News::detail'
        _arguments:
          news_title: news
  defaultController: 'News::detail'
  defaults:
    news_page: '0'
  aspects:
    news_page:
      type: StaticIntegerRangeMapper
      start: 1
      end: 1000
    news_title:
      type: PersistedAliasMapper
      tableName: tx_news_domain_model_news
      routeFieldName: path_segment
  DateNews:
    type: Extbase
    limitToPages: [28]
    extension: News
    plugin: Pi1
    routes:
      # Pagination:
      - routePath: '/page-{page}'
        _controller: 'News::list'
        _arguments:
          page: '@widget_0/currentPage'
        requirements:
          page: '\d+'
      - routePath: '/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news-title: news
      # Date year:
      - routePath: '/{news_year}'
        _controller: 'News::list'
        _arguments:
          news_month: 'overwriteDemand/month'
          news_year: 'overwriteDemand/year'
          page: '@widget_0/currentPage'
        requirements:
          date-year: '\d+'
      # Date year + pagination:
      - routePath: '/{news_year}/page-{page}'
        _controller: 'News::list'
        _arguments:
          news_year: 'overwriteDemand/year'
          page: '@widget_0/currentPage'
        requirements:
          news_year: '\d+'
          page: '\d+'
      # Date year/month:
      - routePath: '/{news_year}/{news_month}'
        _controller: 'News::list'
        _arguments:
          news_month: 'overwriteDemand/month'
          news_year: 'overwriteDemand/year'
          page: '@widget_0/currentPage'
        requirements:
          news_month: '\d+'
          news_year: '\d+'
      # Date year/month + pagination:
      - routePath: '/{news_year}/{news_month}/page-{page}'
        _controller: 'News::list'
        _arguments:
          news_month: 'overwriteDemand/month'
          news_year: 'overwriteDemand/year'
          page: '@widget_0/currentPage'
        requirements:
          news_month: '\d+'
          news_year: '\d+'
          page: '\d+'
      # Date year/month + title
      - routePath: '/{news_year}/{news_month}/{news_title}'
        _controller: 'News::detail'
        _arguments:
          news_month: month
          news_year: year
          news_title: news
    defaultController: 'News::detail'
    aspects:
      news_title:
        type: PersistedAliasMapper
        tableName: tx_news_domain_model_news
        routeFieldName: path_segment
      news_month:
        type: StaticRangeMapper
        start: '1'
        end: '31'
        padString: '0'
        padLength: '2'
        padType: '0'
      news_year:
        type: StaticRangeMapper
        start: '2006'
        end: '2036'
      requirements:
        news_title: \d+
        year: '^20[0-9]{2}$'
        month: '[01][0-9]$'
